version: 2.1.3.{build}
skip_tags: true
configuration: Release
init:
- git config --global core.autocrlf true
build:
  publish_nuget: true
  verbosity: minimal
environment:
  Test.Path: C:\projects\html2markdown\test\Html2Markdown.Test\Files\
  GithubEmail: baynezy@gmail.com
  GithubUsername: baynezy
  GithubPersonalAccessToken:
    secure: 9EkZYUVbHPWlMZLyUqjY79llLHc6DghntcHAodFfiMyOsIc4pbCNNEMv/lTi0SvJ
deploy:
- provider: NuGet
  api_key:
    secure: mqfd5QXj3a2N+D2EP9avxupQJRBJFEKT9kjF7Tipl1OCkUvPBsKjfiZMQHpnwVKq
  on:
    branch: master
install:
  - choco install doxygen.portable
build_script:
  - cmd: >-
      cd %BUILD_DIR%

      dotnet restore
      
      dotnet build

      dotnet pack .\src\Html2Markdown\Html2Markdown.csproj /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
test_script:
  - cmd: >-
      dotnet test .\test\Html2Markdown.Test\Html2Markdown.Test.csproj --logger "trx;LogFileName=results.trx"
after_test:
  - ps: ./uploadTestResults.ps1
  - ps: C:/ProgramData/chocolatey/lib/doxygen.portable/tools/doxygen.exe doxygen.config
  - ps: ./pushDocumentation.ps1 $env:APPVEYOR_BUILD_FOLDER $env:GithubEmail $env:GithubUsername $env:GithubPersonalAccessToken $env:appveyor_repo_branch
notifications:
  - provider: Slack
    auth_token:
      secure: xLrYwFJVzehV+sdSJsDp52X1TSPeSGJrr56LI2GQDvrmkpjcrwX1rmPwdH+i14H8lijQDcWbUt9jl81saehgRA==
    channel: '#build'