version: 3.2.1.{build}
skip_tags: true
configuration: Release
init:
- git config --global core.autocrlf true
install:
- ps: npm install -g markdownlint-cli
- ps: choco install codecov
build:
  publish_nuget: true
  verbosity: minimal
environment:
  Test.Path: C:\projects\html2markdown\test\Html2Markdown.Test\Files\
  GithubEmail: baynezy@gmail.com
  GithubUsername: baynezy
  GithubPersonalAccessToken:
    secure: 9EkZYUVbHPWlMZLyUqjY79llLHc6DghntcHAodFfiMyOsIc4pbCNNEMv/lTi0SvJ
  CodeCovUploadToken:
    secure: CMfvSS5oD40S7KGiXgDbEIwy/d2gMcY6UxOcHWvNxC/CLe000a9TUDkoBXWCUN1p
deploy:
- provider: NuGet
  api_key:
    secure: mqfd5QXj3a2N+D2EP9avxupQJRBJFEKT9kjF7Tipl1OCkUvPBsKjfiZMQHpnwVKq
  on:
    branch: master
build_script:
  - cmd: >-
      cd %BUILD_DIR%

      markdownlint .

      dotnet restore
      
      dotnet build

      dotnet pack .\src\Html2Markdown\Html2Markdown.csproj -c %CONFIGURATION% /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
test_script:
  - cmd: >-
      dotnet test .\test\Html2Markdown.Test\Html2Markdown.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger "trx;LogFileName=results.trx"
after_test:
  - ps: ./pushDocumentation.ps1 $env:APPVEYOR_BUILD_FOLDER $env:GithubEmail $env:GithubUsername $env:GithubPersonalAccessToken $env:appveyor_repo_branch
on_finish:
  - ps: ./uploadTestResults.ps1
  - ps: .\codecov -f .\test\Html2Markdown.Test\Html2Markdown.Test.csproj -t $env:CodeCovUploadToken
artifacts:
- path: src\Html2Markdown\bin\Release\*.nupkg
notifications:
  - provider: Slack
    auth_token:
      secure: xLrYwFJVzehV+sdSJsDp52X1TSPeSGJrr56LI2GQDvrmkpjcrwX1rmPwdH+i14H8lijQDcWbUt9jl81saehgRA==
    channel: '#build'